logging:
  level:
    root: INFO

spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    username: dev
    password: ''
    url: jdbc:h2:mem:devdb
    h2:
      console:
        enabled: true
        path: /h2
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          enable_lazy_load_no_trans: true
      show-sql: true